### ISSUE TITLE
3 Observations 06.05.2024

### ISSUE THREAD

**Issue by ravikanthvishnubhotla** [pannet1/telegram-trades#9]
Observation 1. 2nd Lot is not trailed to cost after 1st Lot Exit.E-Trail Error Observed
I exited all the trades and made only once channel live for execution to have more clarity. Meanwhile, Can you pls check for 2nd Lot handling..is there any change with 2nd Lot handling after Market Entry changes were done?
Can you pls verify the code for 2nd Lot trail SL to cost and exit @ 2nd Target

Observation.2: Stock Options are triggered in MKT and are rejected. should be with LMT Order.

Observation.3: Observation 3: BFO Trades like SENSEX and BANKEX doesnt allow MKT order..So they need to be handled as LMT orders

Attached Json file and Signal file along with the error seen in VPS for your reference
-- Logging error ---
Traceback (most recent call last):
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\logging_init_.py", line 1083, in emit
msg = self.format(record)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\logging_init_.py", line 927, in format
return fmt.format(record)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\logging_init_.py", line 663, in format
record.message = record.getMessage()
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\logging_init_.py", line 367, in getMessage
msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
File "C:\py\venv\telegram-trades\telegram_trades\main.py", line 545, in
run()
File "C:\py\venv\telegram-trades\telegram_trades\main.py", line 520, in run
task = obj_tasks._str_to_func(task)
File "C:\py\venv\telegram-trades\telegram_trades\main.py", line 156, in _str_to_func
return method(**task)
File "C:\py\venv\telegram-trades\telegram_trades\main.py", line 310, in is_stop_or_target1
logging.error("placing trailing stop", resp)
Message: 'placing trailing stop'
Arguments: ([],)

[tasks.json](https://github.com/pannet1/telegram-trades/files/15217612/tasks.json)

[signals.csv](https://github.com/pannet1/telegram-trades/files/15217613/signals.csv)

**Comment by pannet1** [comment]
issues are date aware. no need to add them in the subject line. can you please raise one issue (or observation) at a time.
